- name: Deploy to Kubernetes
  hosts: localhost
  tasks:
    - name: Create deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: devops-app-deployment
            namespace: default
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: devops-app
            template:
              metadata:
                labels:
                  app: devops-app
              spec:
                containers:
                - name: devops-app
                  image: devops-app:latest
                  ports:
                  - containerPort: 8080
                  imagePullPolicy: Never

    - name: Create service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: devops-app-service
            namespace: default
          spec:
            selector:
              app: devops-app
            ports:
            - protocol: TCP
              port: 80
              targetPort: 8080
              nodePort: 30080
            type: NodePort
