---
- name: Deploy Application with Docker
  hosts: docker-hosts
  become: yes
  tasks:
    - name: Stop existing container
      docker_container:
        name: devops-app
        state: stopped
      ignore_errors: yes

    - name: Remove existing container
      docker_container:
        name: devops-app
        state: absent
      ignore_errors: yes

    - name: Remove existing image
      docker_image:
        name: devops-app:latest
        state: absent
      ignore_errors: yes

    - name: Build Docker image
      docker_image:
        name: devops-app:latest
        build:
          path: /var/lib/jenkins/workspace/CI-CD-PIPELINE
        source: build

    - name: Run container
      docker_container:
        name: devops-app
        image: devops-app:latest
        state: started
        ports:
          - "8081:8080"
